// <auto-generated />
namespace DataAcessLayer_HizmetPortal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class mig121 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig121));
        
        string IMigrationMetadata.Id
        {
            get { return "202408070710446_mig121"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
